name: "xmihoyo"
description: "给不看活动的旅行者、开拓者们做了一个小工具."

publish_to: "none"
version: 1.0.2+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2 # 添加这个来确保项目能够请求 HTTP 数据
  intl: ^0.17.0
  connectivity_plus: ^4.0.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_launcher_icons: "^0.9.2"
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  assets:
    - assets/icon.png
    - assets/placeholder.png
  uses-material-design: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png" # 图标路径
